---

#- name: Try to specify preference for mysql
#  shell: echo mysql-apt-config mysql-apt-config/select-server select mysql-8.0 | debconf-set-selections
#  become: yes
#
#- name: Add mysql apt-config debian
#  apt: 
#    deb: http://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
#    update-cache: yes
#  become: yes

- name: Install mySQL
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-mysqldb
    - mysql-server
          
- name: Run mysql
  service:
    name: mysql 
    state: started
    enabled: true

- name: Update mysql root password
  mysql_user: 
    name: root
    host: localhost 
    password: "{{ root_passwd }}"
    login_user: root
    login_password: "{{ root_passwd }}"

- name: Create a new database besides root
  mysql_db:
    name: "{{ dbname }}"
    state: present
    login_user: root
    login_password: "{{ root_passwd }}"

- name: Create user
  mysql_user: 
    name: "{{ username }}"
    host: "%" 
    password: "{{ password }}"
    priv: "{{dbname}}.*:ALL"
    login_user: root
    login_password: "{{ root_passwd }}"

- name: Replace config file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf

- name: Restart mysql
  service:
    name: mysql
    state: restarted