---


- name: Download public key for elastic repo
  shell: curl https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add repo definition
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Download beats
  shell: curl -L -O https://artifacts.elastic.co/downloads/beats/{{ item }}/{{ item }}-6.5.3-amd64.deb
  with_items:
    - metricbeat 
    - packetbeat
    - filebeat

- name: Install beats
  shell: dpkg -i {{ item }}-6.5.3-amd64.deb
  with_items:
    - metricbeat 
    - packetbeat
    - filebeat

- name: Copy config files
  template:
    src: "{{ item }}.yml.j2"
    dest: "/etc/{{ item }}/{{ item }}.yml"
  with_items:
    - metricbeat 
    - packetbeat

- name: Copy filebeat config if log exists
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
  when: log_files is defined

- name: Install dashboards
  shell: "{{ item }} setup"
  with_items:
    - metricbeat 
    - packetbeat

- name: Install dashboards for filebeat
  shell: "filebeat setup"
  when: log_files is defined

- name: Enable modules for metricbeat
  shell: "metricbeat modules enable {{ modules | join(' ') }}"

- name: Install modules for filebeat
  shell: "filebeat modules enable {{ modules | join(' ') }}"
  when: log_files is defined

- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - metricbeat
    - packetbeat
    - filebeat