---



- name: Download public key for elastic repo
  shell: curl https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add repo definition
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Download heartbeat
  shell: curl -L -O https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-6.5.3-amd64.deb

- name: Install heartbeat
  shell: dpkg -i heartbeat-6.5.3-amd64.deb

- name: Copy heartbeat config file
  template:
    src: "heartbeat.yml.j2"
    dest: "/etc/heartbeat/heartbeat.yml"

- name: Sleep
  shell: sleep 120

- name: Install heartbeat dashboards
  shell: "heartbeat setup --dashboards"

- name: Start heartbeat
  service:
    name: "heartbeat-elastic"
    state: started
    enabled: true