---

version: '2'
  ghost:
    image: ghost:latest
    container_name: ghost-blog
    environment:
      - NODE_ENV=production
      - MYSQL_DATABASE={{dbname}} # Change {{db-name}}
      - MYSQL_USER={{username}} # Change {{username}}
      - "MYSQL_PASSWORD={{password}}" # Change {{db-password}}
      - "MAILGUN_USER={{mailgun-user}}" # Change {{mailgun-user}}
      - "MAILGUN_PASSWORD={{mailgun-password}}" # Change {{mailgun-password}}
    volumes:
      - ./ghost:/var/lib/ghost
    ports:
      - 2368:2368
    depends_on:
      - mysql
    restart: always
