---


- name: Create build env for Docker
  file:
    path: /tmp/docker_env
    state: directory

- name: Create Dockerfile
  template:
    src: Dockerfile.j2
    dest: /tmp/docker_env/Dockerfile

- name: Create config.production.json
  template:
    src: Dockerfile.j2
    dest: /tmp/docker_env/Dockerfile

- name: Create Dockerfile
  template:
    src: config.production.json.j2
    dest: /tmp/docker_env/config.production.json

- name: Build Docker image
  docker_image:
    path: /tmp/docker_env
    name: my/ghost

- name: Run docker container in port 80
  docker_container:
    name: ghost_blog
    published_ports:
      - 2368:2368
    image: my/ghost
    detach: false
  async: 3
  poll: 0