---
- set_fact:
    other_node_ext_ip: '{{ groups.database[1] }}'
  when: inventory_hostname == groups.database[0]

- set_fact:
    other_node_int_ip: '{{ hostvars[other_node_ext_ip].ansible_all_ipv4_addresses[0] }}'
  when: inventory_hostname == groups.database[0]


- set_fact:
    node_int_ip: '{{ hostvars[inventory_hostname].ansible_all_ipv4_addresses[0] }}'
  when: inventory_hostname == groups.database[0]


- set_fact:
    priority: '{{ keepalived_priority }}'
  when: inventory_hostname == groups.database[0]

- set_fact:
    state : '{{ keepalived_master_state }}'
  when: inventory_hostname == groups.database[0]




- set_fact:
    other_node_ext_ip: '{{ groups.database[0] }}'
  when: inventory_hostname == groups.database[1]

- set_fact:
    other_node_int_ip: '{{ hostvars[other_node_ext_ip].ansible_all_ipv4_addresses[0] }}'
  when: inventory_hostname == groups.database[1]

- set_fact:
    node_int_ip: '{{ hostvars[inventory_hostname].ansible_all_ipv4_addresses[0] }}'
  when: inventory_hostname == groups.database[1]

- set_fact:
    priority: '{{ keepalived_backup_priority }}'
  when: inventory_hostname == groups.database[1]

- set_fact:
    state : '{{ keepalived_backup_state }}'
  when: inventory_hostname == groups.database[1]


- name: Configure floating IP
  blockinfile:
    path: /etc/network/interfaces
    block: |
      auto ens4:0
      iface ens4:0 inet static
          address {{ keepalived_shared_ip }}
          netmask 255.255.255.255 

- name: Restart network
  service:
    name: networking
    state: restarted

- name: Install keepalived (debian/ubuntu)
  apt: name=keepalived state=latest
  when: ansible_os_family == "Debian"

- name: Configurar keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: Configurar master takeover script 
  template: src=master.sh.j2 dest=/etc/keepalived/master.sh mode='0777'

- name: Configurar backup takeover script
  template: src=backup.sh.j2 dest=/etc/keepalived/backup.sh mode='0777'

- name: Start keepalived
  service: name=keepalived state=started


