---

- name: Allow consuming apps to bind on non local addresses
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.conf.default.arp_ignore
    value: 1
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.conf.default.arp_announce
    value: 2
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.conf.all.arp_ignore
    value: 1
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.conf.all.arp_announce
    value: 2
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 0
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 0
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    sysctl_set: yes
    state: present

- sysctl:
    name: net.ipv4.conf.all.log_martians
    value: 1
    sysctl_set: yes
    state: present