---


- name: Pull elastic search docker image
  docker_image:
    name: elasticsearch
    tag: 6.5.3
    pull: yes

- name: Pull kibana docker image
  docker_image:
    name: kibana
    tag: 6.5.3
    pull: yes

- name: Increase memory capacity
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.max_map_count=262144

- name: Enable ip forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1

- name: Restart sysctl
  command: sysctl --system

- name: Run elasticsearch 
  docker_container:
    name: esearch
    published_ports:
      - 9200:9200
      - 9300:9300 
    image: elasticsearch:6.5.3

- name: Run kibana
  docker_container: 
    name: kibana
    published_ports:
      - 80:5601
    image: kibana:6.5.3
    links:
      - esearch:elasticsearch

- name: Download public key for elastic repo
  shell: curl https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Add repo definition
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Download heartbeat
  shell: curl -L -O https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-6.5.3-amd64.deb

- name: Install heartbeat
  shell: dpkg -i heartbeat-6.5.3-amd64.deb

- name: Copy heartbeat config file
  template:
    src: "heartbeat.yml.j2"
    dest: "/etc/heartbeat/heartbeat.yml"

- name: Sleep
  shell: sleep 120

- name: Install heartbeat dashboards
  shell: "heartbeat setup --dashboards"

- name: Start heartbeat
  service:
    name: "heartbeat-elastic"
    state: started
    enabled: true