---


- name: Pull elastic search docker image
  docker_image:
    name: elasticsearch
    tag: 6.5.3
    pull: yes

- name: Pull kibana docker image
  docker_image:
    name: kibana
    tag: 6.5.3
    pull: yes

- name: Increase memory capacity
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.max_map_count=262144

- name: Enable ip forwarding
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1

- name: Restart sysctl
  command: sysctl --system

- name: Run elasticsearch 
  docker_container:
    name: esearch
    published_ports:
      - 9200:9200
      - 9300:9300 
    image: elasticsearch:6.5.3

- name: Run kibana
  docker_container: 
    name: kibana
    published_ports:
      - 80:5601
    image: kibana:6.5.3
    links:
      - esearch:elasticsearch