---


- name: Add docker repo key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install required software
  apt:
    name: "{{ item }}"
    state: latest
  with_items: 
    - docker-ce

- name: Install pip
  apt:
    name: python-pip
    state: latest

- name: Install docker-py for ansible docker modules
  command: pip install docker-py